### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by dworthen2** [gov4git/dworthen-project-repo#34]
### Your public repo

https://github.com/dworthen2/gov4git-identity-public.git

### Your public branch

main

**Comment by dworthen** [comment]
Approve

**Comment by dworthen** [comment]
dworthen2 added to community.

**Comment by dworthen** [comment]
dworthen2 added to community.

**Comment by dworthen** [comment]
dworthen2 added to community.
